---
# Source: splunk-otel-collector/charts/operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: operator
  namespace: default
  labels:
    helm.sh/chart: operator-0.88.3
    app.kubernetes.io/name: operator
    app.kubernetes.io/version: "0.124.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: opentelemetry-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/component: controller-manager
